name: binaries

on:
  push:
    # tags:
      # - '*'
    branches:
      - 'ci'
jobs:
  publish:
    strategy:
      fail-fast: true
    name: publish
    runs-on: ubuntu-20.04
    steps:
      - uses: dtolnay/rust-toolchain@1.66.1
        with:
          components: rustfmt

######## CACHE ########
      - name: apt packages
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: build-essential ca-certificates clang curl git libpq-dev libssl-dev pkg-config lsof lld libgmp-dev
          version: 1.0
      # - name: install protoc and related tools
      #   shell: bash
      #   run: ./scripts/dev_setup.sh -b -r


      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
        with:
          cache-all-crates: true
          cache-on-failure: true

######## BUILD ########

      - name: cargo release build
        run: cargo b --release -p aptos-node

######## PUBLISH ########

      - name: publish
        uses: taiki-e/upload-rust-binary-action@v1
        with:
          # (required) Comma-separated list of binary names (non-extension portion of filename) to build and upload.
          # Note that glob pattern is not supported yet.
          bin: aptos, aptos-node
          # (required) GitHub token for uploading assets to GitHub Releases.
          token: ${{ secrets.GITHUB_TOKEN }}

